### ISSUE TITLE
Toggle component is displayed incorrectly

### ISSUE THREAD

**Issue by pavelhoral** [WrenSecurity/wrensec-ui#16]
We have switched titatoggle library for a newer version and that version is incorrectly rendered with shifted knob:

![image](https://user-images.githubusercontent.com/2012726/210354328-cc6330b9-c973-4874-8cdb-a848eef483e5.png)

This issue is in both AM and IdM and is caused by the following CSS:

```css
.form-horizontal [class^="checkbox"] input + span::after {
  top: 7px;
}
```
